### PR TITLE
Refactor detector into a module and add Base64 Decoding

### PR DESCRIPTION
**Pull request by JasonKeirstead**
- Refactor the detector into a module so that it can be called from other places (ie threat hunting notebooks)
- Add a sample for Base64 obfuscation
- Handle Base64 obfuscation in a more robust way vs looking only for a full string

### CODE REVIEW

**Comment by Neo23x0** [comment]
Do we really have to rename the python script name? Because of the `-` in the name? 
This would most likely break some guides / scripts that use it.

**Comment by JasonKeirstead** [comment]
The original script has the same name. I took the core detection code and moved it into a python module so that it can be loaded outside of the mainline executable. This will let people use it in jupyter threat hunt books

**Comment by Neo23x0** [comment]
Understood. But we would have to change the "Getting started" and explain that users have to copy the complete folder to the target system and remove the ./tests/ folder before they do that to avoid moving maliciously looking payloads to their systems. 

People using jupyter notebooks don't have top priority. 
Normal users don't care much about that when you just want to bring a tool to a target system and run it once. I think many users use Ansible scripts to perform that task today. I wonder how they would copy and use Log4shell-detector as a module. 

Maybe it's better to compress the tests in a password protected ZIP and decompress them before the testing.

**Comment by Neo23x0** [comment]
Or .. provide it as "releases" that are ZIPs without the ./tests folder.

**Comment by Neo23x0** [comment]
Or release it on pypi.org ... but I guess that most system administrators don't like to install packages from pypi for a one-time task

**Comment by JasonKeirstead** [comment]
Agree it is probably a long haul to publish this on Pypi - but you can install it directly from git from a notebook

python -m pip install git+https://github.com/JasonKeirstead/log4shell-detector/

I see what you're saying about the tests though, will try to figure out a solution

**Comment by Neo23x0** [comment]
Maybe we can store the tests in a gziped + base64 encoded data blob and save them to disk a the beginning of the test runs.

**Comment by Neo23x0** [comment]
I'll refactor the tests

**Comment by Neo23x0** [comment]
https://github.com/Neo23x0/log4shell-detector/pull/30/

**Pull request merged**
